allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

ext {
    flutter = [
        compileSdkVersion: 35,
        minSdkVersion: 21,
        targetSdkVersion: 35,
        versionCode: 1,
        versionName: '1.0.0',
        ndkVersion: '25.1.8937393' // Standard NDK version
    ]
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
